app.message=Hello from ORDER DEV Config Server
app.environment=DEV
server.port=8082

user.service.base-url=http://localhost:8081

resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=500ms
logging.level.io.github.resilience4j.retry=DEBUG
